### ISSUE TITLE
bug 提示

### ISSUE THREAD

**Issue by helong123456** [zhayujie/fabric-tools#5]
你在add-org.js中 直接var orgs = ORGS我的确没看懂

**Comment by zhayujie** [comment]
> 你在add-org.js中 直接var orgs = ORGS我的确没看懂

这里确实是我没有说清楚上下文，这句代码为了获取全部的组织信息。 
add-org.js 需要放在balance-transfer/app下， 引用了helper.js文件， 在helper.js中有一个全局变量 (第27行)：

`var ORGS = hfc.getConfigSetting('network-config');`

所以add-org.js中可以直接使用ORG进行赋值。
